# Generated by Django 4.2.7 on 2025-11-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(help_text='Height in cm or ft/in', max_length=10)),
                ('skin_tone', models.CharField(choices=[('Fair/Light', 'Fair/Light'), ('Wheatish', 'Wheatish'), ('Dark', 'Dark')], max_length=20)),
                ('body_type', models.CharField(choices=[('Slim', 'Slim'), ('Fit', 'Fit'), ('Fat', 'Fat')], max_length=10)),
                ('favourite_colors', models.JSONField(default=list, help_text='List of favorite colors')),
                ('preferred_clothing_types', models.JSONField(default=list, help_text='List of preferred clothing types')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Style Profile',
                'verbose_name_plural': 'User Style Profiles',
            },
        ),
    ]
